robot_config:
  ros__parameters:
    robot_parent: "world"
    robot_groups:
      robot1:
        simulation_controllers: robot1_controller.yaml
        robot_name: "robot1"
        robot_type: "ur10"
        urdf_file: "robot_system/robot_system.xacro"
        vacuum_gripper_prefix: "vacuum_gripper1_"
        gripper_plugin_name: "gripper1"
        controller_names:
          ["robot1_joint_state_broadcaster", "robot1_controller"]
        x: 0.5
        y: 1.8
        z: 0.95
        initial_positions_file: "robot1_zeros.yaml"
      robot2:
        simulation_controllers: robot2_controller.yaml
        robot_name: "robot2"
        robot_type: "ur5"
        urdf_file: "robot_system/robot_system.xacro"
        vacuum_gripper_prefix: "vacuum_gripper2_"
        gripper_plugin_name: "gripper2"
        controller_names:
          ["robot2_joint_state_broadcaster", "robot2_controller"]
        x: -7.8
        y: -1.5
        z: 0.7
        yaw: 1.57
        initial_positions_file: "robot2_zeros.yaml"
      mobile_robot:
        robot_name: "turtlebot"
        x: -4.0
        y: -0.2
        z: 0.0
