robot1:
  controller_manager:
    ros__parameters:
      update_rate: 50 # Hz
  
      robot1_forward_position_controller:
        type: forward_command_controller/ForwardCommandController
  
      robot1_joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster
  
  robot1_forward_position_controller:
    ros__parameters:
      joints:
        - robot1_shoulder_pan_joint
        - robot1_shoulder_lift_joint
        - robot1_elbow_joint
        - robot1_wrist_1_joint
        - robot1_wrist_2_joint
        - robot1_wrist_3_joint      
      interface_name: position
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
        - effort
  
  